[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
libCode = { path = "../libCode"}
tokio = { version = "1.44.1", features = ["rt", "rt-multi-thread", "macros", "net", "io-std", "io-util", "sync", "time"] }
serde = "1.0.219"
serde_json = "1.0"